### ISSUE TITLE
stop youtube on close

### ISSUE THREAD

**Issue by kiwigringo** [fnagel/MultiDialog#11]
issue on Opera and Chrome (ok on Firefox)
When dialog is closed youtube audio keeps playing in background, and clicking on trigger to open dialog a second time creates a new instance of youtube clip.
It's possible to end up with many hidden youtube clips all playing in the background if a user clicks to open a dialog mulitple times.

See:
https://developers.google.com/youtube/iframe_api_reference
for YouTube iframes api reference which may help to control youtube clips.

**Comment by fnagel** [comment]
Closed as no feedback was given. Please reopen if needed.
